version: 3.8
services: 

  nodejs:
    image: node:latest
    ports: 
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - /path/to/repository:/app
    workdir: /app

   
      



