name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Close running container
      id: close
      run: docker stop laurellinks

    - uses: actions/checkout@v3
    - name: Delete previous container
      id: delete
      run: docker system prune -f 

    - uses: actions/checkout@v3  
    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag laurellinks:latest

    - uses: actions/checkout@v3
    - name: Deploy the docker container
      id: deploy
      run: docker run --rm --name laurellinks  -p 3000:3000 -d laurellinks:latest
      if: steps.build.outcome == 'success'


